# This is a basic workflow that is manually triggered

name: Build and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches:
            - "main"

jobs:
    check-publish-ready:
        uses: ./.github/workflows/code-quality.yml

    get-version:
        runs-on: ubuntu-latest
        outputs:
            VITE_APP_VERSION: ${{ steps.package-version.outputs.VITE_APP_VERSION }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - id: package-version
              run: echo "VITE_APP_VERSION=$(jq -r .version package.json )" >> "$GITHUB_OUTPUT"

    publish:
        runs-on: ubuntu-latest
        needs: [check-publish-ready, get-version]
        env:
            VITE_APP_VERSION: ${{ needs.get-version.outputs.VITE_APP_VERSION }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: 🌍 Check Environment Variables
              run: |
                  echo "VITE APP VERSION: ${{ env.VITE_APP_VERSION }}"

            - name: ⚙️ Configure Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  registry-url: "https://registry.npmjs.org"

            - name: ⚙️ Inspect NPM & Node Version
              run: |
                  echo Node Version: `node --version`
                  echo NPM Version: `npm --version`

            - name: 🔨 Install Dependencies and Build
              run: npm install && npm run build

            - name: 📦 Publish package on NPM
              if: github.ref == 'refs/heads/main'
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}

    create-pull-request:
        runs-on: ubuntu-latest
        needs: [get-version, publish]
        env:
            VITE_APP_VERSION: ${{ needs.get-version.outputs.VITE_APP_VERSION }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions/checkout@v4
              with:
                  repository: incendiarybean/benweare-ts-server
                  path: benweare-ts-server
                  token: ${{ secrets.ACCESS_TOKEN }}
                  ref: development

            - name: 💬 Submit Pull Request on benweare-ts-server
              if: github.ref == 'refs/heads/main'
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              run: |
                  cd benweare-ts-server

                  # Configure and clone
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"

                  BRANCH_NAME="CHORE-client-${{ env.VITE_APP_VERSION }}"

                  # Install latest dependencies and update the client
                  npm install --quiet
                  npm install benweare.co.uk-client@${{ env.VITE_APP_VERSION }} --quiet

                  # Commit the changes and push the feature branch to origin
                  git checkout -b $BRANCH_NAME
                  git commit -am "CHORE: Bump client to ${{ env.VITE_APP_VERSION }}"
                  git push origin $BRANCH_NAME

                  # Create PR on server repo
                  gh pr create \
                    --body "AUTOMATED: Bump to ${{ env.VITE_APP_VERSION }}" \
                    --title "CHORE: Bump client to ${{ env.VITE_APP_VERSION }}" \
                    --head "$BRANCH_NAME" \
                    --base "development"

            - name: ⚠️ Retry on failed attempt
              if: failure() && github.run_attempt < 4
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  echo "Workflow Run: ${{ github.run_id }} failed, attempting to retry... (Attempt ${{ github.run_attempt }} out of 4)"
                  gh workflow run retry.yml --ref ${{github.ref}} -F run_id=${{ github.run_id }}
