# This is a basic workflow that is manually triggered

name: Build and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches:
            - "*"

jobs:
    # check-publish-ready:
    #     uses: ./.github/workflows/code-quality.yml

    publish:
        runs-on: ubuntu-latest
        # needs: [check-publish-ready]
        env:
            REACT_APP_NAME: ${{ secrets.APP_NAME }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: 🔎 Get Package version
              run: |
                  echo "VITE_APP_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1 )" >> $GITHUB_ENV

            - name: 🌍 Check Environment Variables
              if: github.ref == 'refs/heads/feature'
              run: |
                  echo "VITE APP VERSION: $VITE_APP_VERSION"

            # - name: ⚙️ Configure Node.js environment
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: '18'
            #       registry-url: 'https://registry.npmjs.org'

            # - name: ⚙️ Configure NPM
            #   run: |
            #       npm i -g npm@9
            #       echo Node Version: `node --version`
            #       echo NPM Version: `npm --version`

            # - name: 🔨 Install dependencies and build
            #   run: npm install && npm run build

            # - name: 🧼 Run Linter
            #   run: npm run lint

            # - name: 🧪 Run Tests
            #   run: npm test

            # - name: 📦 Publish package on NPM
            #   if: github.ref == 'refs/heads/main'
            #   run: npm publish --access public
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}

    create-pull-request:
        runs-on: ubuntu-latest
        needs: [publish]
        env:
            GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}
                  path: benweare-ts-client

            - uses: actions/checkout@v4
              with:
                  repository: incendiarybean/benweare-ts-server
                  path: benweare-ts-server

            - name: 💬 Submit Pull Request on benweare-ts-server
              # if: github.ref == 'refs/heads/main'
              run: |
                  # Configure and clone
                  git config --global user.name "${GITHUB_ACTOR}"
                  git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

                  BRANCH_NAME="CHORE-client-$VITE_APP_VERSION"

                  cd benweare-ts-server

                  # Install latest dependencies and update the client
                  npm install --quiet
                  npm install benweare.co.uk-client@1.7.2 --quiet

                  # Commit the changes and push the feature branch to origin
                  git checkout -b $BRANCH_NAME
                  git commit -am "CHORE: Bump client to $VITE_APP_VERSION"
                  git push origin $BRANCH_NAME

                  # Create a PR on the branch of benweare-ts-server
                  gh auth login
                  gh pr create \
                    --body "AUTOMATED: Bump to $VITE_APP_VERSION" \
                    --title "CHORE: Bump client to $VITE_APP_VERSION" \
                    --head "$BRANCH_NAME" \
                    --base "development"

            - name: Retry on failed attempt
              if: failure()
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  cd benweare-ts-client
                  gh workflow run retry.yml -F run_id=${{ github.run_id }}
