# This is a basic workflow that is manually triggered

name: Build and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches:
            - "*"

jobs:
    # check-publish-ready:
    #     uses: ./.github/workflows/code-quality.yml

    get_version:
        runs-on: ubuntu-latest
        outputs:
            VITE_APP_VERSION: ${{ steps.package_version.outputs.VITE_APP_VERSION }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - id: package_version
              run: echo "VITE_APP_VERSION=$(jq -r .version package.json )" >> "$GITHUB_OUTPUT"

    publish:
        runs-on: ubuntu-latest
        # needs: [check-publish-ready]
        needs: [get_version]
        env:
            REACT_APP_NAME: ${{ secrets.APP_NAME }}
            VITE_APP_VERSION: ${{ needs.get_version.outputs.VITE_APP_VERSION }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: 🌍 Check Environment Variables
              run: |
                  echo "VITE APP VERSION: ${{ env.VITE_APP_VERSION }}"

            # - name: ⚙️ Configure Node.js environment
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: '18'
            #       registry-url: 'https://registry.npmjs.org'

            # - name: ⚙️ Configure NPM
            #   run: |
            #       npm i -g npm@9
            #       echo Node Version: `node --version`
            #       echo NPM Version: `npm --version`

            # - name: 🔨 Install dependencies and build
            #   run: npm install && npm run build

            # - name: 🧼 Run Linter
            #   run: npm run lint

            # - name: 🧪 Run Tests
            #   run: npm test

            # - name: 📦 Publish package on NPM
            #   if: github.ref == 'refs/heads/main'
            #   run: npm publish --access public
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}

    create-pull-request:
        runs-on: ubuntu-latest
        needs: [get_version, publish]
        env:
            GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            VITE_APP_VERSION: ${{ needs.get_version.outputs.VITE_APP_VERSION }}

        steps:
            - uses: actions/checkout@v4
              with:
                  repository: incendiarybean/benweare-ts-server
                  path: benweare-ts-server
                  token: ${{ secrets.ACCESS_TOKEN }}

            - name: ⬆️ Upgrade NPM client package version
              # if: github.ref == 'refs/heads/main'
              run: |
                  cd benweare-ts-server

                  # Configure and clone
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"

                  BRANCH_NAME="CHORE-client-${{ env.VITE_APP_VERSION }}"

                  # Install latest dependencies and update the client
                  npm install --quiet
                  npm install benweare.co.uk-client@${{ env.VITE_APP_VERSION }} --quiet

                  # Commit the changes and push the feature branch to origin
                  git checkout -b $BRANCH_NAME
                  git commit -am "CHORE: Bump client to ${{ env.VITE_APP_VERSION }}"
                  git push origin $BRANCH_NAME

            - name: 💬 Submit Pull Request on benweare-ts-server
              run: |
                  cd benweare-ts-server

                  gh auth login
                  gh pr create \
                    --body "AUTOMATED: Bump to ${{ env.VITE_APP_VERSION }}" \
                    --title "CHORE: Bump client to ${{ env.VITE_APP_VERSION }}" \
                    --head "$BRANCH_NAME" \
                    --base "development"

            - uses: actions/checkout@v4
              if: failure()
              with:
                  ref: ${{ github.ref }}
                  path: benweare-ts-client

            - name: ⚠️ Retry on failed attempt
              if: failure() && github.run_attempt < 3
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  cd benweare-ts-client
                  gh workflow run retry.yml --ref ${{github.ref}} -F run_id=${{ github.run_id }}
