# This is a basic workflow that is manually triggered

name: Build and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches:
            - main
            - '*'
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            REACT_APP_NAME: ${{ secrets.APP_NAME }}

        steps:
            - uses: actions/checkout@v4

            - name: 🔎 Get Package version
              run: |
                  echo "REACT_APP_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1 )" >> $GITHUB_ENV

            # - name: 🌍 Check Environment Variables
            #   if: github.ref == 'refs/heads/feature'
            #   run: |
            #       echo "REACT APP VERSION: $REACT_APP_VERSION"

            # - name: ⚙️ Configure Node.js environment
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: '18'
            #       registry-url: 'https://registry.npmjs.org'

            # - name: ⚙️ Configure NPM
            #   run: |
            #       npm i -g npm@9
            #       echo Node Version: `node --version`
            #       echo NPM Version: `npm --version`

            # - name: 🔨 Install dependencies and build
            #   run: npm install && npm run build

            # - name: 🧼 Run Linter
            #   run: npm run lint

            # - name: 🧪 Run Tests
            #   run: npm test

            # - name: 📦 Publish package on NPM
            #   if: github.ref == 'refs/heads/main'
            #   run: npm publish --access public
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}

            - name: 👇 Pull benweare-server-ts
              # if: github.ref == 'refs/heads/main'
              uses: actions/checkout@v4
              with:
                  repository: incendiarybean/benweare-ts-server
                  token: ${{ secrets.ACCESS_TOKEN }}
                  path: benweare-ts-server

            - name: 💬 Submit Pull Request on benweare-ts-server
              # if: github.ref == 'refs/heads/main'
              env:
                  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              run: |
                  cd benweare-ts-server

                  # Configure
                  git config --global user.name "${GITHUB_ACTOR}"
                  git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

                  BRANCH_NAME="CHORE-client-$REACT_APP_VERSION"

                  # Install latest dependencies and update the client
                  npm install --quiet
                  npm install benweare.co.uk-client --quiet

                  # Commit the changes and push the feature branch to origin
                  git checkout -b $BRANCH_NAME development
                  git commit -am "CHORE: Bump client to $REACT_APP_VERSION"
                  git push origin $BRANCH_NAME

                  # Create a PR on the branch of benweare-ts-server
                  gh pr create \
                    --body "AUTOMATED: Bump to $REACT_APP_VERSION" \
                    --title "CHORE: Bump client to $REACT_APP_VERSION" \
                    --head "$BRANCH_NAME" \
                    --base "development"
