name: Rerun on failure

on:
    workflow_dispatch:
        inputs:
            run_id:
                required: true
jobs:
    rerun:
        runs-on: ubuntu-latest
        steps:
            - name: Retry on failed attempt
              if: failure()
              env:
                  GH_REPO: ${{ github.repository }}
                  GH_TOKEN: ${{ github.token }}
              run: |
                  echo "Attempt: ${{ github.run_attempt }}"
                  gh run rerun ${{ inputs.run_id }} --failed
