# This is a basic cypress workflow that is automatically triggered

name: Build and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    workflow_call:
    push:
        branches:
            - '*'
            - '!main'
    pull_request:
        branches:
            - '*'
            - '!main'

jobs:
    lint-code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: 🧼 Run Linter
              run: |
                  npm install --quiet
                  npm run lint

    cypress-test:
        runs-on: ubuntu-latest
        needs: [lint-code]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: 🔨 Cypress install
              uses: cypress-io/github-action@v6
              with:
                  runTests: false
                  build: npm run build

            - name: 💾 Save build folder
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  if-no-files-found: error
                  path: build

            - name: ⬇️ Download the build folder
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: build

            - name: 🧪 Cypress Test
              uses: cypress-io/github-action@v6
              with:
                  start: npm start
                  browser: chrome
                  project: |
                      ./cypress
                      ./src
